#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteKinhDoanhDoGoCuongThai.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDoGo")]
	public partial class QLDoGoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLOAIHANG(LOAIHANG instance);
    partial void UpdateLOAIHANG(LOAIHANG instance);
    partial void DeleteLOAIHANG(LOAIHANG instance);
    partial void InsertCHITIETHANGHOA(CHITIETHANGHOA instance);
    partial void UpdateCHITIETHANGHOA(CHITIETHANGHOA instance);
    partial void DeleteCHITIETHANGHOA(CHITIETHANGHOA instance);
    partial void InsertDONDATHANG(DONDATHANG instance);
    partial void UpdateDONDATHANG(DONDATHANG instance);
    partial void DeleteDONDATHANG(DONDATHANG instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertLIENHE(LIENHE instance);
    partial void UpdateLIENHE(LIENHE instance);
    partial void DeleteLIENHE(LIENHE instance);
    partial void InsertHOMTHU(HOMTHU instance);
    partial void UpdateHOMTHU(HOMTHU instance);
    partial void DeleteHOMTHU(HOMTHU instance);
    partial void InsertHANGHOA(HANGHOA instance);
    partial void UpdateHANGHOA(HANGHOA instance);
    partial void DeleteHANGHOA(HANGHOA instance);
    #endregion
		
		public QLDoGoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLDoGoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDoGoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDoGoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDoGoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDoGoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOAIHANG> LOAIHANGs
		{
			get
			{
				return this.GetTable<LOAIHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHANGHOA> CHITIETHANGHOAs
		{
			get
			{
				return this.GetTable<CHITIETHANGHOA>();
			}
		}
		
		public System.Data.Linq.Table<DONDATHANG> DONDATHANGs
		{
			get
			{
				return this.GetTable<DONDATHANG>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<LIENHE> LIENHEs
		{
			get
			{
				return this.GetTable<LIENHE>();
			}
		}
		
		public System.Data.Linq.Table<HOMTHU> HOMTHUs
		{
			get
			{
				return this.GetTable<HOMTHU>();
			}
		}
		
		public System.Data.Linq.Table<HANGHOA> HANGHOAs
		{
			get
			{
				return this.GetTable<HANGHOA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIHANG")]
	public partial class LOAIHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiHang;
		
		private string _TenLoaiHang;
		
		private EntitySet<HANGHOA> _HANGHOAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiHangChanging(string value);
    partial void OnMaLoaiHangChanged();
    partial void OnTenLoaiHangChanging(string value);
    partial void OnTenLoaiHangChanged();
    #endregion
		
		public LOAIHANG()
		{
			this._HANGHOAs = new EntitySet<HANGHOA>(new Action<HANGHOA>(this.attach_HANGHOAs), new Action<HANGHOA>(this.detach_HANGHOAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiHang
		{
			get
			{
				return this._MaLoaiHang;
			}
			set
			{
				if ((this._MaLoaiHang != value))
				{
					this.OnMaLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHang = value;
					this.SendPropertyChanged("MaLoaiHang");
					this.OnMaLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiHang", DbType="NVarChar(20)")]
		public string TenLoaiHang
		{
			get
			{
				return this._TenLoaiHang;
			}
			set
			{
				if ((this._TenLoaiHang != value))
				{
					this.OnTenLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiHang = value;
					this.SendPropertyChanged("TenLoaiHang");
					this.OnTenLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_HANGHOA", Storage="_HANGHOAs", ThisKey="MaLoaiHang", OtherKey="MaLoaiHang")]
		public EntitySet<HANGHOA> HANGHOAs
		{
			get
			{
				return this._HANGHOAs;
			}
			set
			{
				this._HANGHOAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HANGHOAs(HANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHANG = this;
		}
		
		private void detach_HANGHOAs(HANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.LOAIHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHANGHOA")]
	public partial class CHITIETHANGHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMatHang;
		
		private int _MaDonDatHang;
		
		private decimal _SoLuong;
		
		private decimal _SoTien;
		
		private EntityRef<DONDATHANG> _DONDATHANG;
		
		private EntityRef<HANGHOA> _HANGHOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMatHangChanging(string value);
    partial void OnMaMatHangChanged();
    partial void OnMaDonDatHangChanging(int value);
    partial void OnMaDonDatHangChanged();
    partial void OnSoLuongChanging(decimal value);
    partial void OnSoLuongChanged();
    partial void OnSoTienChanging(decimal value);
    partial void OnSoTienChanged();
    #endregion
		
		public CHITIETHANGHOA()
		{
			this._DONDATHANG = default(EntityRef<DONDATHANG>);
			this._HANGHOA = default(EntityRef<HANGHOA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMatHang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMatHang
		{
			get
			{
				return this._MaMatHang;
			}
			set
			{
				if ((this._MaMatHang != value))
				{
					if (this._HANGHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMatHangChanging(value);
					this.SendPropertyChanging();
					this._MaMatHang = value;
					this.SendPropertyChanged("MaMatHang");
					this.OnMaMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonDatHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDonDatHang
		{
			get
			{
				return this._MaDonDatHang;
			}
			set
			{
				if ((this._MaDonDatHang != value))
				{
					if (this._DONDATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonDatHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonDatHang = value;
					this.SendPropertyChanged("MaDonDatHang");
					this.OnMaDonDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Decimal(3,0) NOT NULL")]
		public decimal SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Decimal(18,0) NOT NULL")]
		public decimal SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this.OnSoTienChanging(value);
					this.SendPropertyChanging();
					this._SoTien = value;
					this.SendPropertyChanged("SoTien");
					this.OnSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CHITIETHANGHOA", Storage="_DONDATHANG", ThisKey="MaDonDatHang", OtherKey="MaDonDatHang", IsForeignKey=true)]
		public DONDATHANG DONDATHANG
		{
			get
			{
				return this._DONDATHANG.Entity;
			}
			set
			{
				DONDATHANG previousValue = this._DONDATHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONDATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONDATHANG.Entity = null;
						previousValue.CHITIETHANGHOAs.Remove(this);
					}
					this._DONDATHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETHANGHOAs.Add(this);
						this._MaDonDatHang = value.MaDonDatHang;
					}
					else
					{
						this._MaDonDatHang = default(int);
					}
					this.SendPropertyChanged("DONDATHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANGHOA_CHITIETHANGHOA", Storage="_HANGHOA", ThisKey="MaMatHang", OtherKey="MaMatHang", IsForeignKey=true)]
		public HANGHOA HANGHOA
		{
			get
			{
				return this._HANGHOA.Entity;
			}
			set
			{
				HANGHOA previousValue = this._HANGHOA.Entity;
				if (((previousValue != value) 
							|| (this._HANGHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HANGHOA.Entity = null;
						previousValue.CHITIETHANGHOAs.Remove(this);
					}
					this._HANGHOA.Entity = value;
					if ((value != null))
					{
						value.CHITIETHANGHOAs.Add(this);
						this._MaMatHang = value.MaMatHang;
					}
					else
					{
						this._MaMatHang = default(string);
					}
					this.SendPropertyChanged("HANGHOA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONDATHANG")]
	public partial class DONDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonDatHang;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<bool> _HinhThucThanhToan;
		
		private System.Nullable<System.DateTime> _NgayGiaoHang;
		
		private System.Nullable<bool> _TinhTrangThanhToan;
		
		private System.Nullable<bool> _TinhTrangGiao;
		
		private System.Nullable<int> _MaKhachHang;
		
		private string _HoTenNguoiNhan;
		
		private string _DiaChiNguoiNhan;
		
		private string _SoDienThoaiNguoiNhan;
		
		private EntitySet<CHITIETHANGHOA> _CHITIETHANGHOAs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonDatHangChanging(int value);
    partial void OnMaDonDatHangChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnHinhThucThanhToanChanging(System.Nullable<bool> value);
    partial void OnHinhThucThanhToanChanged();
    partial void OnNgayGiaoHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoHangChanged();
    partial void OnTinhTrangThanhToanChanging(System.Nullable<bool> value);
    partial void OnTinhTrangThanhToanChanged();
    partial void OnTinhTrangGiaoChanging(System.Nullable<bool> value);
    partial void OnTinhTrangGiaoChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    partial void OnHoTenNguoiNhanChanging(string value);
    partial void OnHoTenNguoiNhanChanged();
    partial void OnDiaChiNguoiNhanChanging(string value);
    partial void OnDiaChiNguoiNhanChanged();
    partial void OnSoDienThoaiNguoiNhanChanging(string value);
    partial void OnSoDienThoaiNguoiNhanChanged();
    #endregion
		
		public DONDATHANG()
		{
			this._CHITIETHANGHOAs = new EntitySet<CHITIETHANGHOA>(new Action<CHITIETHANGHOA>(this.attach_CHITIETHANGHOAs), new Action<CHITIETHANGHOA>(this.detach_CHITIETHANGHOAs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonDatHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonDatHang
		{
			get
			{
				return this._MaDonDatHang;
			}
			set
			{
				if ((this._MaDonDatHang != value))
				{
					this.OnMaDonDatHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonDatHang = value;
					this.SendPropertyChanged("MaDonDatHang");
					this.OnMaDonDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucThanhToan", DbType="Bit")]
		public System.Nullable<bool> HinhThucThanhToan
		{
			get
			{
				return this._HinhThucThanhToan;
			}
			set
			{
				if ((this._HinhThucThanhToan != value))
				{
					this.OnHinhThucThanhToanChanging(value);
					this.SendPropertyChanging();
					this._HinhThucThanhToan = value;
					this.SendPropertyChanged("HinhThucThanhToan");
					this.OnHinhThucThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoHang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiaoHang
		{
			get
			{
				return this._NgayGiaoHang;
			}
			set
			{
				if ((this._NgayGiaoHang != value))
				{
					this.OnNgayGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoHang = value;
					this.SendPropertyChanged("NgayGiaoHang");
					this.OnNgayGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangThanhToan", DbType="Bit")]
		public System.Nullable<bool> TinhTrangThanhToan
		{
			get
			{
				return this._TinhTrangThanhToan;
			}
			set
			{
				if ((this._TinhTrangThanhToan != value))
				{
					this.OnTinhTrangThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangThanhToan = value;
					this.SendPropertyChanged("TinhTrangThanhToan");
					this.OnTinhTrangThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangGiao", DbType="Bit")]
		public System.Nullable<bool> TinhTrangGiao
		{
			get
			{
				return this._TinhTrangGiao;
			}
			set
			{
				if ((this._TinhTrangGiao != value))
				{
					this.OnTinhTrangGiaoChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangGiao = value;
					this.SendPropertyChanged("TinhTrangGiao");
					this.OnTinhTrangGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenNguoiNhan", DbType="NVarChar(50)")]
		public string HoTenNguoiNhan
		{
			get
			{
				return this._HoTenNguoiNhan;
			}
			set
			{
				if ((this._HoTenNguoiNhan != value))
				{
					this.OnHoTenNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._HoTenNguoiNhan = value;
					this.SendPropertyChanged("HoTenNguoiNhan");
					this.OnHoTenNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiNguoiNhan", DbType="NVarChar(50)")]
		public string DiaChiNguoiNhan
		{
			get
			{
				return this._DiaChiNguoiNhan;
			}
			set
			{
				if ((this._DiaChiNguoiNhan != value))
				{
					this.OnDiaChiNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._DiaChiNguoiNhan = value;
					this.SendPropertyChanged("DiaChiNguoiNhan");
					this.OnDiaChiNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoaiNguoiNhan", DbType="VarChar(15)")]
		public string SoDienThoaiNguoiNhan
		{
			get
			{
				return this._SoDienThoaiNguoiNhan;
			}
			set
			{
				if ((this._SoDienThoaiNguoiNhan != value))
				{
					this.OnSoDienThoaiNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoaiNguoiNhan = value;
					this.SendPropertyChanged("SoDienThoaiNguoiNhan");
					this.OnSoDienThoaiNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONDATHANG_CHITIETHANGHOA", Storage="_CHITIETHANGHOAs", ThisKey="MaDonDatHang", OtherKey="MaDonDatHang")]
		public EntitySet<CHITIETHANGHOA> CHITIETHANGHOAs
		{
			get
			{
				return this._CHITIETHANGHOAs;
			}
			set
			{
				this._CHITIETHANGHOAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONDATHANG", Storage="_KHACHHANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.DONDATHANGs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.DONDATHANGs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHANGHOAs(CHITIETHANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.DONDATHANG = this;
		}
		
		private void detach_CHITIETHANGHOAs(CHITIETHANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.DONDATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _SoTaiKhoan;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntitySet<DONDATHANG> _DONDATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnSoTaiKhoanChanging(string value);
    partial void OnSoTaiKhoanChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._DONDATHANGs = new EntitySet<DONDATHANG>(new Action<DONDATHANG>(this.attach_DONDATHANGs), new Action<DONDATHANG>(this.detach_DONDATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTaiKhoan", DbType="VarChar(50)")]
		public string SoTaiKhoan
		{
			get
			{
				return this._SoTaiKhoan;
			}
			set
			{
				if ((this._SoTaiKhoan != value))
				{
					this.OnSoTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._SoTaiKhoan = value;
					this.SendPropertyChanged("SoTaiKhoan");
					this.OnSoTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_DONDATHANG", Storage="_DONDATHANGs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<DONDATHANG> DONDATHANGs
		{
			get
			{
				return this._DONDATHANGs;
			}
			set
			{
				this._DONDATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONDATHANGs(DONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_DONDATHANGs(DONDATHANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAdmin;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private System.Nullable<bool> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdminChanging(int value);
    partial void OnMaAdminChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnPhanQuyenChanging(System.Nullable<bool> value);
    partial void OnPhanQuyenChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAdmin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaAdmin
		{
			get
			{
				return this._MaAdmin;
			}
			set
			{
				if ((this._MaAdmin != value))
				{
					this.OnMaAdminChanging(value);
					this.SendPropertyChanging();
					this._MaAdmin = value;
					this.SendPropertyChanged("MaAdmin");
					this.OnMaAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen", DbType="Bit")]
		public System.Nullable<bool> PhanQuyen
		{
			get
			{
				return this._PhanQuyen;
			}
			set
			{
				if ((this._PhanQuyen != value))
				{
					this.OnPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._PhanQuyen = value;
					this.SendPropertyChanged("PhanQuyen");
					this.OnPhanQuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LIENHE")]
	public partial class LIENHE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLienHen;
		
		private string _CoSoSanXuat;
		
		private string _DienThoai;
		
		private string _Mobile;
		
		private string _Fax;
		
		private string _EmailLienHe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLienHenChanging(int value);
    partial void OnMaLienHenChanged();
    partial void OnCoSoSanXuatChanging(string value);
    partial void OnCoSoSanXuatChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEmailLienHeChanging(string value);
    partial void OnEmailLienHeChanged();
    #endregion
		
		public LIENHE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLienHen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLienHen
		{
			get
			{
				return this._MaLienHen;
			}
			set
			{
				if ((this._MaLienHen != value))
				{
					this.OnMaLienHenChanging(value);
					this.SendPropertyChanging();
					this._MaLienHen = value;
					this.SendPropertyChanged("MaLienHen");
					this.OnMaLienHenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoSoSanXuat", DbType="NVarChar(100)")]
		public string CoSoSanXuat
		{
			get
			{
				return this._CoSoSanXuat;
			}
			set
			{
				if ((this._CoSoSanXuat != value))
				{
					this.OnCoSoSanXuatChanging(value);
					this.SendPropertyChanging();
					this._CoSoSanXuat = value;
					this.SendPropertyChanged("CoSoSanXuat");
					this.OnCoSoSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(20)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailLienHe", DbType="VarChar(50)")]
		public string EmailLienHe
		{
			get
			{
				return this._EmailLienHe;
			}
			set
			{
				if ((this._EmailLienHe != value))
				{
					this.OnEmailLienHeChanging(value);
					this.SendPropertyChanging();
					this._EmailLienHe = value;
					this.SendPropertyChanged("EmailLienHe");
					this.OnEmailLienHeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOMTHU")]
	public partial class HOMTHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThu;
		
		private string _TenNguoiGui;
		
		private string _Email;
		
		private string _ChuDe;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayGui;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuChanging(int value);
    partial void OnMaThuChanged();
    partial void OnTenNguoiGuiChanging(string value);
    partial void OnTenNguoiGuiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnChuDeChanging(string value);
    partial void OnChuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGuiChanged();
    #endregion
		
		public HOMTHU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThu
		{
			get
			{
				return this._MaThu;
			}
			set
			{
				if ((this._MaThu != value))
				{
					this.OnMaThuChanging(value);
					this.SendPropertyChanging();
					this._MaThu = value;
					this.SendPropertyChanged("MaThu");
					this.OnMaThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiGui", DbType="NVarChar(50)")]
		public string TenNguoiGui
		{
			get
			{
				return this._TenNguoiGui;
			}
			set
			{
				if ((this._TenNguoiGui != value))
				{
					this.OnTenNguoiGuiChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiGui = value;
					this.SendPropertyChanged("TenNguoiGui");
					this.OnTenNguoiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(50)")]
		public string ChuDe
		{
			get
			{
				return this._ChuDe;
			}
			set
			{
				if ((this._ChuDe != value))
				{
					this.OnChuDeChanging(value);
					this.SendPropertyChanging();
					this._ChuDe = value;
					this.SendPropertyChanged("ChuDe");
					this.OnChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(400)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGui", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGui
		{
			get
			{
				return this._NgayGui;
			}
			set
			{
				if ((this._NgayGui != value))
				{
					this.OnNgayGuiChanging(value);
					this.SendPropertyChanging();
					this._NgayGui = value;
					this.SendPropertyChanged("NgayGui");
					this.OnNgayGuiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANGHOA")]
	public partial class HANGHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMatHang;
		
		private string _MaLoaiHang;
		
		private string _TenMatHang;
		
		private string _KichThuoc;
		
		private string _LoaiGo;
		
		private string _MoTa;
		
		private string _HinhAnh;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private string _LinkThanhToan;
		
		private decimal _DonGia;
		
		private decimal _KhuyenMai;
		
		private string _BaoHanh;
		
		private System.Nullable<bool> _BanChay;
		
		private System.Nullable<decimal> _GiaMoi;
		
		private EntitySet<CHITIETHANGHOA> _CHITIETHANGHOAs;
		
		private EntityRef<LOAIHANG> _LOAIHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMatHangChanging(string value);
    partial void OnMaMatHangChanged();
    partial void OnMaLoaiHangChanging(string value);
    partial void OnMaLoaiHangChanged();
    partial void OnTenMatHangChanging(string value);
    partial void OnTenMatHangChanged();
    partial void OnKichThuocChanging(string value);
    partial void OnKichThuocChanged();
    partial void OnLoaiGoChanging(string value);
    partial void OnLoaiGoChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnLinkThanhToanChanging(string value);
    partial void OnLinkThanhToanChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnKhuyenMaiChanging(decimal value);
    partial void OnKhuyenMaiChanged();
    partial void OnBaoHanhChanging(string value);
    partial void OnBaoHanhChanged();
    partial void OnBanChayChanging(System.Nullable<bool> value);
    partial void OnBanChayChanged();
    partial void OnGiaMoiChanging(System.Nullable<decimal> value);
    partial void OnGiaMoiChanged();
    #endregion
		
		public HANGHOA()
		{
			this._CHITIETHANGHOAs = new EntitySet<CHITIETHANGHOA>(new Action<CHITIETHANGHOA>(this.attach_CHITIETHANGHOAs), new Action<CHITIETHANGHOA>(this.detach_CHITIETHANGHOAs));
			this._LOAIHANG = default(EntityRef<LOAIHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMatHang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMatHang
		{
			get
			{
				return this._MaMatHang;
			}
			set
			{
				if ((this._MaMatHang != value))
				{
					this.OnMaMatHangChanging(value);
					this.SendPropertyChanging();
					this._MaMatHang = value;
					this.SendPropertyChanged("MaMatHang");
					this.OnMaMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiHang
		{
			get
			{
				return this._MaLoaiHang;
			}
			set
			{
				if ((this._MaLoaiHang != value))
				{
					if (this._LOAIHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiHangChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHang = value;
					this.SendPropertyChanged("MaLoaiHang");
					this.OnMaLoaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMatHang", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string TenMatHang
		{
			get
			{
				return this._TenMatHang;
			}
			set
			{
				if ((this._TenMatHang != value))
				{
					this.OnTenMatHangChanging(value);
					this.SendPropertyChanging();
					this._TenMatHang = value;
					this.SendPropertyChanged("TenMatHang");
					this.OnTenMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuoc", DbType="NVarChar(200)")]
		public string KichThuoc
		{
			get
			{
				return this._KichThuoc;
			}
			set
			{
				if ((this._KichThuoc != value))
				{
					this.OnKichThuocChanging(value);
					this.SendPropertyChanging();
					this._KichThuoc = value;
					this.SendPropertyChanged("KichThuoc");
					this.OnKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiGo", DbType="NVarChar(50)")]
		public string LoaiGo
		{
			get
			{
				return this._LoaiGo;
			}
			set
			{
				if ((this._LoaiGo != value))
				{
					this.OnLoaiGoChanging(value);
					this.SendPropertyChanging();
					this._LoaiGo = value;
					this.SendPropertyChanged("LoaiGo");
					this.OnLoaiGoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(300)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(20)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkThanhToan", DbType="NVarChar(MAX)")]
		public string LinkThanhToan
		{
			get
			{
				return this._LinkThanhToan;
			}
			set
			{
				if ((this._LinkThanhToan != value))
				{
					this.OnLinkThanhToanChanging(value);
					this.SendPropertyChanging();
					this._LinkThanhToan = value;
					this.SendPropertyChanged("LinkThanhToan");
					this.OnLinkThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(12,0) NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="Decimal(12,0) NOT NULL")]
		public decimal KhuyenMai
		{
			get
			{
				return this._KhuyenMai;
			}
			set
			{
				if ((this._KhuyenMai != value))
				{
					this.OnKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai = value;
					this.SendPropertyChanged("KhuyenMai");
					this.OnKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="VarChar(20)")]
		public string BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BanChay", DbType="Bit")]
		public System.Nullable<bool> BanChay
		{
			get
			{
				return this._BanChay;
			}
			set
			{
				if ((this._BanChay != value))
				{
					this.OnBanChayChanging(value);
					this.SendPropertyChanging();
					this._BanChay = value;
					this.SendPropertyChanged("BanChay");
					this.OnBanChayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaMoi", AutoSync=AutoSync.Always, DbType="Decimal(32,6)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> GiaMoi
		{
			get
			{
				return this._GiaMoi;
			}
			set
			{
				if ((this._GiaMoi != value))
				{
					this.OnGiaMoiChanging(value);
					this.SendPropertyChanging();
					this._GiaMoi = value;
					this.SendPropertyChanged("GiaMoi");
					this.OnGiaMoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANGHOA_CHITIETHANGHOA", Storage="_CHITIETHANGHOAs", ThisKey="MaMatHang", OtherKey="MaMatHang")]
		public EntitySet<CHITIETHANGHOA> CHITIETHANGHOAs
		{
			get
			{
				return this._CHITIETHANGHOAs;
			}
			set
			{
				this._CHITIETHANGHOAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIHANG_HANGHOA", Storage="_LOAIHANG", ThisKey="MaLoaiHang", OtherKey="MaLoaiHang", IsForeignKey=true)]
		public LOAIHANG LOAIHANG
		{
			get
			{
				return this._LOAIHANG.Entity;
			}
			set
			{
				LOAIHANG previousValue = this._LOAIHANG.Entity;
				if (((previousValue != value) 
							|| (this._LOAIHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIHANG.Entity = null;
						previousValue.HANGHOAs.Remove(this);
					}
					this._LOAIHANG.Entity = value;
					if ((value != null))
					{
						value.HANGHOAs.Add(this);
						this._MaLoaiHang = value.MaLoaiHang;
					}
					else
					{
						this._MaLoaiHang = default(string);
					}
					this.SendPropertyChanged("LOAIHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHANGHOAs(CHITIETHANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.HANGHOA = this;
		}
		
		private void detach_CHITIETHANGHOAs(CHITIETHANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.HANGHOA = null;
		}
	}
}
#pragma warning restore 1591
